### ISSUE TITLE
Convert avatar (Uint8List) to File

### ISSUE THREAD

**Issue by yadaniyil** [fluttercommunity/flutter_contacts#101]
I'm not able to convert contact's avatar to File.
I tried to 
File file = File.fromRawPath(contact.avatar); 
But this file seems corrupted because I cannot use Image.file with it or upload to Firebase Storage. 

How to convert avatar to File?

**Comment by yadaniyil** [comment]
Solution: save the file locally and then use it

**Comment by ayazkhalid** [comment]
> Solution: save the file locally and then use it
can u share the solution??

**Comment by flomingdev** [comment]
can you provide some basic example?
