### ISSUE TITLE
ContactsService.getContacts() returns empty array

### ISSUE THREAD

**Issue by marwan-at-work** [fluttercommunity/flutter_contacts#103]
If you run the example folder of this repo under the latest stable Flutter build, the home page doesn't have any contacts even though the iOS simulator has some.

**Comment by lukasgit** [comment]
@marwan-at-work are you still having this issue? I'm unable to reproduce on my end.

**Comment by sdemisse** [comment]
I am having same issue

**Comment by lukasgit** [comment]
@marwan-at-work and @sdemisse repo maintained at https://github.com/lukasgit/flutter_contacts/
