### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method getAvatar on channel 

### ISSUE THREAD

**Issue by AhsanAyaz** [fluttercommunity/flutter_contacts#110]
When running on iOS simulator, it always throws this error:

![image](https://user-images.githubusercontent.com/9844254/79641291-e11be280-8196-11ea-8d21-ae9842b0cfc9.png)

Currently running on iPhone 11 simulator

**Comment by lukasgit** [comment]
@AhsanAyaz this repo has moved. Please see https://github.com/fluttercommunity/flutter_contacts/issues/107#issue-529150243
