### ISSUE TITLE
when we run project in ios then gives error 

### ISSUE THREAD

**Issue by reeteshverma39** [fluttercommunity/flutter_contacts#18]
/Users/prateeksuraj/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.0.6/ios/Classes/ContactsServicePlugin.m:2:9: fatal error: 'contacts_service/contacts_service-Swift.h' file not found
#import <contacts_service/contacts_service-Swift.h>

**Comment by mavimo** [comment]
@reeteshverma39 same issue here, do you find some solution?

**Comment by clovisnicolas** [comment]
Could you update to 0.0.7 and tell me if you still have the issue ?

**Comment by mavimo** [comment]
@clovisnicolas I'll do in few hours (I'm out of office now)

**Comment by mavimo** [comment]
Same issue here:
```
Launching lib/main.dart on iPhone X in debug mode...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **
Xcode's output:
↳
=== BUILD TARGET contacts_service OF PROJECT Pods WITH CONFIGURATION Debug ===
/Users/marco/Development/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.0.7/ios/Classes/ContactsServicePlugin.m:2:9: fatal error: 'contacts_service/contacts_service-Swift.h' file not found
#import <contacts_service/contacts_service-Swift.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.
Exited (sigterm)
```
more info:
```
marco@genesi ~/Development/mavimo/test_app master → flutter doctor -v
[✓] Flutter (Channel unknown, v0.5.6, on Mac OS X 10.13.6 17G65, locale en-IT)
    • Flutter version 0.5.6 at /Users/marco/Development/flutter
    • Framework revision 472bbccf75 (2 weeks ago), 2018-06-26 17:01:46 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/marco/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • iPhone X • 1CBB7331-32F6-4D26-BF30-D4CBA12CD169 • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by mavimo** [comment]
@clovisnicolas after some more investigation seems that:

 - Header file is missing [here](https://github.com/clovisnicolas/flutter_contacts/blob/master/ios/Classes/ContactsServicePlugin.m#L2) but I see other plugins that also miss it like [flutter_audio](https://github.com/rxlabz/flutter_audio/blob/master/ios/Classes/AudioplayerPlugin.m)
 - Version is wrong [here](https://github.com/clovisnicolas/flutter_contacts/blob/master/ios/contacts_service.podspec#L6) but I see that other plugins have the [same issue](https://github.com/rxlabz/flutter_audio/blob/master/ios/audioplayer.podspec#L6)

NB: I'm not iOS mobile developer and I do not have expertise in swift language :)

**Comment by mavimo** [comment]
@clovisnicolas maybe was my fault, I create a new project with flag `-i swift` and now work as expected! Sorry for the noise, maybe add this info in README can help to reduce noise in issues.

PS: I do not find how to migrate a project to support swift, any idea? :)

**Comment by clovisnicolas** [comment]
Ok thanks for the info, I'll close this for now

**Comment by reeteshverma39** [comment]
Thanks guys i will check ASAP
