### ISSUE TITLE
Is WRITE_CONTACTS permission required if only read methods used?

### ISSUE THREAD

**Issue by dmjones** [fluttercommunity/flutter_contacts#23]
The README states:

> Make sure you add the following permissions to your Android Manifest
> ```
> <uses-permission android:name="android.permission.READ_CONTACTS" />
> <uses-permission android:name="android.permission.WRITE_CONTACTS" />
> ```

Is `WRITE_CONTACTS` required if I only plan to read the contact information?

**Comment by clovisnicolas** [comment]
You should be fine by just setting READ_CONTACTS.
