### ISSUE TITLE
The phone numbers are duplicate.

### ISSUE THREAD

**Issue by bucketclan** [fluttercommunity/flutter_contacts#24]
**Case 1**
When I have a single number associated with a contact.

For each contact it is showing two numbers like `74113 61788` and `7411361788`. 
So basically it has a number with spaces and a number without spaces.

The same contact in my phone book app shows just a single number.

**Case 2**
When I have two numbers associated with a contact.

If I have a contact with two different numbers like `77777777` and `66666 6666`, then it shows properly that is the two numbers with exact spacing.

I have an android 6.0 which is pure android. I making use of the default android contacts app.

**Comment by ThinkDigitalSoftware** [comment]
You may have to consider that the contacts are linked in your previous phone and being shown as a single contact, but they're broken up when restored. This is an issue I'm having as well

**Comment by lukasgit** [comment]
Closing this issue as there's been a lack of interest in the community regarding this issue. If someone wants to contribute their solution, I will gladly re-open this issue for discussion. Thanks!
