### ISSUE TITLE
Invalid envelope on Android

### ISSUE THREAD

**Issue by Mania-1024** [fluttercommunity/flutter_contacts#25]
Hi, I'm trying to use your plugin but I can't make the example work. Whenever I launch the app and call the service, I get this stacktrace : 

```
Launching lib\main.dart on SM G903F in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk (30.3MB).
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate(30339): onResume setting current activity to this
Syncing files to device SM G903F...
D/libGLESv2(30339): DTS_GLAPI : DTS is not allowed for Package : <my package>
D/libGLESv1(30339): DTS_GLAPI : DTS is not allowed for Package : <my package>
D/ViewRootImpl(30339): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(30339): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(30339): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(30339): ViewPostImeInputStage processPointer 1
E/flutter (30339): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (30339): FormatException: Invalid envelope
E/flutter (30339): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:546:7)
E/flutter (30339): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
E/flutter (30339): <asynchronous suspension>
E/flutter (30339): #2      ContactsService.addContact (package:contacts_service/contacts_service.dart:20:57)
E/flutter (30339): #3      _MyHomePageState.doWork (<my working directory>/sandbox/lib/main.dart:126:27)
E/flutter (30339): <asynchronous suspension>
E/flutter (30339): #4      _MyHomePageState._incrementCounter (<my working directory>/sandbox/lib/main.dart:58:5)
E/flutter (30339): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
E/flutter (30339): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
E/flutter (30339): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (30339): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (30339): #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
E/flutter (30339): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (30339): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter (30339): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (30339): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (30339): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (30339): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (30339): #16     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (30339): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

I suppose your plugin works, so I'm missing some step, but which one ?

**Comment by clovisnicolas** [comment]
Do you still have the issue with the latest version of flutter & this plugin?

**Comment by zeyadkhaled** [comment]
Hello I am still having this issue

`[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (14173): FormatException: Invalid envelope
E/flutter (14173): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:549:7)
E/flutter (14173): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (14173): <asynchronous suspension>
E/flutter (14173): #2      ContactsService.addContact (package:contacts_service/contacts_service.dart:18:16)
E/flutter (14173): #3      ViewContactsState.actionButton.<anonymous closure> (file:///E:/Flutterprojects/temp_contact/lib/main.dart:143:14)
E/flutter (14173): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
E/flutter (14173): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
E/flutter (14173): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (14173): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (14173): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
E/flutter (14173): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (14173): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (14173): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (14173): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter (14173): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (14173): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (14173): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (14173): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (14173): #17     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (14173): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)`


I am trying to call the method this way:

`onPressed: () {
        ContactsService
            .addContact(new Contact(givenName: "Zeyad", familyName: "App"));
      }`
