### ISSUE TITLE
Takes so much time comparing native android

### ISSUE THREAD

**Issue by yeahia2508** [fluttercommunity/flutter_contacts#32]
To fetch my contact native android code take almost no time but this package takes 5-10 sec to load my contact. That's too much time.

      getContacts() async{
    var contacts = await ContactsService.getContacts();

    setState(() {
      _contacts = contacts;

      Navigator.pushReplacement(
          context,
          MaterialPageRoute(
          builder: (context) => ChatHome(user: widget.user, contacts: _contacts,))
      );
    });

    }

**Comment by salanfe** [comment]
same issue

**Comment by clovisnicolas** [comment]
Hello, this probably has to do with thumbnails getting fetched by default.
There should be an optional parameter bool withThumbnails when fetching contacts.
I don't know when I'll have time to do this, so if anyone has some free time i'll gladly look into your PR

**Comment by yeahia2508** [comment]
is there any update on this issue?

**Comment by lukasgit** [comment]
@yeahia2508 PR #52 added. Closing this issue. Let us know if you're still experiencing problems after upgrading to the latest version of Flutter and contacts_service. Thanks!

**Comment by jayasio** [comment]
Is there any way to lazy load/get paginated contacts, if I need to load with thumbnails?

**Comment by jayasio** [comment]
@lukasgit Is there any way to lazy load/get paginated contacts, if I need to load with thumbnails?

**Comment by lukasgit** [comment]
@jayasio There's a number of things that can be improved and it's on our todo list. Check out the latest version that was recently pushed (0.2.8 - many thanks to @budo385 for this contribution).
