### ISSUE TITLE
Could you public toMap() of Contact class

### ISSUE THREAD

**Issue by isoos** [fluttercommunity/flutter_contacts#35]
_From @lucyhoang on September 14, 2018 1:41_

URL: https://pub.dartlang.org/packages/contacts_service#-readme-tab-

Hi, could you public toMap function of Contact class?

_Copied from original issue: dart-lang/pub-dartlang-dart#1610_

**Comment by isoos** [comment]
@lucyhoang: this repository is for the pub site, please file issues to the package's repository. I'm moving this now.

**Comment by ThinkDigitalSoftware** [comment]
@lucyhoang, I have made a pull request already for that method. Please see https://github.com/clovisnicolas/flutter_contacts/pull/33

**Comment by lukasgit** [comment]
Added in latest PR #82
