### ISSUE TITLE
Feature: Support choosing the account in the phone to add the contact to.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [fluttercommunity/flutter_contacts#37]
I'm not sure how this can be done programmatically, we would have to use Android intents to do so.

**Comment by clovisnicolas** [comment]
Would this apply to iOS as well?

**Comment by ThinkDigitalSoftware** [comment]
I honestly don't know. I've never seen an option to choose a syncing account for newly created contacts.

**Comment by ThinkDigitalSoftware** [comment]
I can check

**Comment by ThinkDigitalSoftware** [comment]
Yes it does, @clovisnicolas. Sorry for the huge photo. It's posted straight from iOS...
![8487c725-96c9-4bd7-be01-fef05810d5f0](https://user-images.githubusercontent.com/23037821/46036929-a4bbf980-c0bb-11e8-894a-b7954ab3815a.jpeg)

**Comment by lukasgit** [comment]
Closing this issue due to lack of interest from the community in choosing accounts in the phone to add a contact. Feel free to chime in if you'd like to contribute and I will re-open this issue. Thanks!

**Comment by ThinkDigitalSoftware** [comment]
I do feel this is a necessity since the contacts apps allow for It, we should be able to duplicate the functionality programmatically. I would say that code should be able to support all customer facing features plus features a dev could use for extra functionality. Does that make any sense?
