### ISSUE TITLE
IOS build fails without using use_frameworks! in Podfile

### ISSUE THREAD

**Issue by solid-vovabeloded** [fluttercommunity/flutter_contacts#38]
Cannot build on IOS 

Xcode's output:
↳
    /Users/vovabeloded/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.0.8/ios/Classes/ContactsServicePlugin.m:4:17: error: definition of 'ContactsServicePlugin' must be imported from module 'contacts_service.ContactsServicePlugin' before it is required
    @implementation ContactsServicePlugin
                    ^
    In module 'contacts_service' imported from /Users/vovabeloded/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.0.8/ios/Classes/ContactsServicePlugin.m:2:
    /Users/vovabeloded/Dev/fbh/fbh_app/build/ios/Debug-iphonesimulator/contacts_service/contacts_service.framework/Headers/ContactsServicePlugin.h:3:12: note: previous definition is here
    @interface ContactsServicePlugin : NSObject<FlutterPlugin>
               ^
    /Users/vovabeloded/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.0.8/ios/Classes/ContactsServicePlugin.m:6:4: warning: 'SwiftContactsServicePlugin' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      [SwiftContactsServicePlugin registerWithRegistrar:registrar];
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'contacts_service' imported from /Users/vovabeloded/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.0.8/ios/Classes/ContactsServicePlugin.m:2:
    /Users/vovabeloded/Dev/fbh/fbh_app/build/ios/Debug-iphonesimulator/contacts_service/contacts_service.framework/Headers/contacts_service-Swift.h:189:12: note: 'SwiftContactsServicePlugin' has been explicitly marked partial here
    @interface SwiftContactsServicePlugin : NSObject <FlutterPlugin>
               ^
    /Users/vovabeloded/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.0.8/ios/Classes/ContactsServicePlugin.m:6:4: note: enclose 'SwiftContactsServicePlugin' in an @available check to silence this warning
      [SwiftContactsServicePlugin registerWithRegistrar:registrar];
       ^~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by clovisnicolas** [comment]
Hello, did you create your project with swift support?

**Comment by solid-vovabeloded** [comment]
I've tried with swift and with obj-c support. The same problem in both projects

**Comment by jeroen-meijer** [comment]
@vova-beloded Do you still have this problem?

**Comment by lukasgit** [comment]
@vova-beloded upgrading to the latest version of Flutter and contacts_service should resolve your issue. I'll close this issue since we haven't heard from you in awhile. Please open a new issue if you run into problems after upgrading to the latest version of Flutter and contacts_service. Thanks!
