### ISSUE TITLE
contacts_service 0.0.4 isn't working 

### ISSUE THREAD

**Issue by EphronKarthick** [fluttercommunity/flutter_contacts#4]
I have used flutter contacts_service 0.0.4 plugin for get contacts, it is works fine on android version 4.4.2, but in android version 6.0.1, it could not fetch contacts on android mobile device. 

So please guide me how to solve the issue.

**Comment by clovisnicolas** [comment]
Can you make sure permissions are enabled on the 6.0.1 device ? The plugin does not ask for them by default

**Comment by EphronKarthick** [comment]
Thanks for your comments. 
Now i enabled the permission for my app, its working fine..
