### ISSUE TITLE
Add optional parameter withThumbnails when fetching contacts

### ISSUE THREAD

**Issue by clovisnicolas** [fluttercommunity/flutter_contacts#40]
By default, all thumbnails are fetched. There should be an optional parameter to specify whether contacts should be fetched with or without the thumbnails.
This would probably fix #32

**Comment by zoechi** [comment]
Wouldn't it be better to fetch thumbnails only on demand?
`getThumbnailForContact(...)`
If I load all contacts and the user doesn't scroll to the end of the list, it might fetch a lot of thumbnails for nothing.

**Comment by clovisnicolas** [comment]
Right, I forgot there is no way to load a particular contact with a given Id.
I still guess it would be nice to have the option to load contacts with or without thumbnails, but we could indeed have another method to either :
- Get the thumbnail for a given Contact (as you said)
or
- Query for a single contact (with a given Id?), with or without thumbnails. This would also allow us to get updates on a single contact without getting all of them again.

**Comment by lukasgit** [comment]
Added via PR #52
