### ISSUE TITLE
The specified Android SDK Build Tools version (25.0.3) is ignored

### ISSUE THREAD

**Issue by JesusZapata** [fluttercommunity/flutter_contacts#46]
Hello I have one trouble with the next line

https://github.com/clovisnicolas/flutter_contacts/blob/f62e1e7b52476c85f71afe93d363438f6b839bdd/android/build.gradle#L30

```
The specified Android SDK Build Tools version (25.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
```

**Comment by lukasgit** [comment]
@JesusZapata are you still experiencing this issue with the latest Flutter and contacts_service build?

**Comment by JesusZapata** [comment]
@lukasgit No, I updated the version of Flutter and the version of contacts_service and all work fine.
Thanks
