### ISSUE TITLE
Can't build project with contacts_service is a dependency

### ISSUE THREAD

**Issue by heromeister** [fluttercommunity/flutter_contacts#47]
When trying to run my flutter project I get this error in the terminal:

```
* Error running Gradle:
ProcessException: Process "D:\Programming\Flutter\on_my_way\android\gradlew.bat" exited abnormally:

> Configure project :contacts_service

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':contacts_service'.
> Could not resolve all artifacts for configuration ':contacts_service:classpath'.
   > Could not find com.android.tools:common:25.3.3.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/android/tools/common/25.3.3/common-25.3.3.pom
       - https://jcenter.bintray.com/com/android/tools/common/25.3.3/common-25.3.3.jar
       - https://maven.google.com/com/android/tools/common/25.3.3/common-25.3.3.pom
       - https://maven.google.com/com/android/tools/common/25.3.3/common-25.3.3.jar
     Required by:
         project :contacts_service > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3
         project :contacts_service > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.build:manifest-merger:25.3.3
         project :contacts_service > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.ddms:ddmlib:25.3.3
         project :contacts_service > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.analytics-library:shared:25.3.3
         project :contacts_service > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.analytics-library:tracker:25.3.3
         project :contacts_service > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools:sdklib:25.3.3 >
         com.android.tools.layoutlib:layoutlib-api:25.3.3
         project :contacts_service > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools:sdklib:25.3.3 >
         com.android.tools:dvlib:25.3.3
         project :contacts_service > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools:sdklib:25.3.3 >
         com.android.tools:repository:25.3.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: D:\Programming\Flutter\on_my_way\android\gradlew.bat app:properties


Please review your Gradle project setup in the android/ folder.
```

The places contacts_service looks for those build tools return 404. 
Here's my gradle file: 
```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {       
        classpath 'com.android.tools.build:gradle:3.2.1' 
    }
}

allprojects {
    repositories {
        maven { url "https://maven.google.com" }
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by bcollins19** [comment]
I am getting a similar issue (except it is the gradle version that cannot be found)

```
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':contacts_service'.
> Could not resolve all files for configuration ':contacts_service:classpath'.
   > Could not find com.android.tools.build:gradle:2.3.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
         https://maven.google.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
         https://maven.google.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
     Required by:
         project :contacts_service

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
  Command: /Users/brettcollins/repos/Expt/apps/ql_shoot/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
```

Here is my build.gradle:
```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.google.gms:google-services:3.2.1'   // new
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by lukasgit** [comment]
@AmitToren @bcollins19 are you still experiencing this issue with the latest Flutter and contacts_service build?

**Comment by heromeister** [comment]
My solution was to open a new project completely and that worked for some reason. I deleted the old project so I don't have a way to check it.

**Comment by lukasgit** [comment]
I'll close this issue for now and re-open if you're able to reproduce later.

**Comment by alcampospalacios** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':contacts_service'.
> Could not resolve all files for configuration ':contacts_service:classpath'.
   > Could not find bundletool-0.13.2.jar (com.android.tools.build:bundletool:0.13.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.13.2/bundletool-0.13.2.jar
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':contacts_service' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':contacts_service' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
Exception: Gradle task assembleDevDebug failed with exit code 1

// *************************************************** Flutter Doctor *******************************************
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22000.1455], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.2)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.74.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

// **************************************************** Build  Gradle ***************************************************
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

***************************************************** Gradle Wrapper Properties ********************************************
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip


I have two days and I can not resolve this issue, any help over here.

**Comment by Brain-codes** [comment]
I am still having this issue, not seen a solution yet.
