### ISSUE TITLE
Request: Avatar (ie Thumbnail)

### ISSUE THREAD

**Issue by freewheelnat** [fluttercommunity/flutter_contacts#5]
Hi there, 
I am aware providing thumbnails is on your to do list, I'm opening this issue to find out if you want help with the Android code for this. 

I've done an Android app, using Flutter, where I fetch contacts including their avatars, so I have Android code I could add to this project, but I don't have iOS code, and I don't know iOS, so my PR would only be for Android. 

The app I have done it for is Preset SMSs https://play.google.com/store/apps/details?id=net.cogitas.presetsms If you install it and add a Preset SMS, it will open another screen and it should show you list of contacts with avatars when available. 

Let me know if you want help on this. I am currently working on a Flutter (Android only for now) project for a client and we need avatars for contacts. We are currently using your plugin, but lack of avatar is blocking us, so either I'll write our own plugin, or I can help you with avatars for Android for your plugin (which would be more useful for other Flutter developers!).

**Comment by clovisnicolas** [comment]
Hello,

I've added a "thumnbails" branch, you can make a pull request on this branch with the android code, i'll try to do the iOS version afterwards asap

**Comment by freewheelnat** [comment]
Thanks a lot! I'll do that next week, probably on Wednesday.

**Comment by freewheelnat** [comment]
I've had a few delays on my side, so PR will probably be late this week/early next week rather than tomorrow, I need to finish something else before I get started on this.

**Comment by freewheelnat** [comment]
See PR https://github.com/clovisnicolas/flutter_contacts/pull/10

**Comment by clovisnicolas** [comment]
Done, thanks for doing the Android & shared code :)
Next step would be adding a parameter withThumbnails on getContacts to only fetch the images if needed

**Comment by freewheelnat** [comment]
You're welcome. Thanks to you for updating the plugin already! :-)
