### ISSUE TITLE
Feature: Support Fax as a label for Phone

### ISSUE THREAD

**Issue by yokiran** [fluttercommunity/flutter_contacts#58]
Besides Work, Mobile and Home, can Fax be added as label please.

**Comment by gotgot1995** [comment]
Hi.

Every other labels would be greatly appreciated as well. Maybe a Map<String,String> to check if the field is present?

Personally, I need to loop over the "labels" (from Android contact). Any idea of how to do that ?

**Comment by trinqk** [comment]
@gotgot1995 I'm working on support for more labels, but updating contacts is a higher priority at the moment so this particular request may be delayed. PRs are definitely welcome. Also, perhaps you could try something like this to loop over the "labels".

```dart
contacts.phones.map((i) {
    print("Label: ${i.label}");
    print("Value: ${i.value}");
});
```

**Comment by trinqk** [comment]
Added via PR [#73](https://github.com/fluttercommunity/flutter_contacts/pull/73). Please use the latest version ```contacts_service: ^0.2.4```
