### ISSUE TITLE
INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed

### ISSUE THREAD

**Issue by weiwill** [fluttercommunity/flutter_contacts#62]
Two Apps cannot be installed on the same phone after using this plug-in

`Error: ADB exited with exit code 1
adb: failed to install /Users/jgwei/IdeaProjects/loan/build/app/outputs/apk/app.apk: Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.ysh.sdb--5GF3pMkE5_bKqOwmq56_g==: Can't install because provider name com.zt.shareextend.fileprovider (in package com.ysh.sdb) is already used by com.ysh.xzsd]
Error launching application on LON AL00.`

contacts_service: ^0.1.1

It seems to be the reason for using share_extend plug-in

Now I can only use the old version.

**Comment by lukasgit** [comment]
@weiwill we are going to pull the share_extend plug-in on the next version release

**Comment by lukasgit** [comment]
@weiwill share_extend removed in PR #87 please upgrade to the latest plugin
