### ISSUE TITLE
Contacts Saved on Google cloud are not fetched

### ISSUE THREAD

**Issue by lambasoft** [fluttercommunity/flutter_contacts#66]
Is it normal for contacts available in the phone contact's list but saved only on Google account not to be fetched from the plugin?

It seems that android phones can sync with your google contacts, but without physically adding the contact to your phone. So the plugin can't fetch these contacts?

**Comment by lukasgit** [comment]
@lambasoft the contacts_service plugin does not retrieve Google cloud contacts, only contacts stored on the device.

Is your device configured to sync with Google cloud?
https://productforums.google.com/d/msg/gmail/Dke6yNT_qyE/1hySMDfnBAAJ

**Comment by lukasgit** [comment]
@lambasoft ^^

**Comment by lambasoft** [comment]
Sorry for the late reply.
You were correct, the device in question wasn't synced with Google Cloud.
