### ISSUE TITLE
Feature request: Open phone contacts list for contact selection

### ISSUE THREAD

**Issue by guyzk** [fluttercommunity/flutter_contacts#71]
This is a very useful feature that I believe many apps could use.
Add a function that opens the phones contact list (instead of importing the whole list into the app) for a single or multiple contact(s) selection and data retrieval.
For example, I want the possibility to fill in a user form with all the details of a specific contact out of my contacts list.
Thanks in advance.

**Comment by lukasgit** [comment]
@guyzk Thanks for the feature request. We review all feature requests and prioritize them accordingly. To speed up the development cycle, we also welcome the community to participate in implementing new features!

**Comment by lukasgit** [comment]
Please submit issues and PR's to https://github.com/lukasgit/flutter_contacts
