### ISSUE TITLE
Deleted contact under Android is still there with empty data

### ISSUE THREAD

**Issue by eisdrachl** [fluttercommunity/flutter_contacts#72]
## 🐛 Bug Report

After calling await ContactsService.deleteContact(contact); the contact is not really deleted under Android. The contact is still in the contact list, but listed as "(no name)". I tested it on real devices having Android 5 and Android 8, I got the same result for both.

### Expected behavior

It would be perfect if the contact deletes completely from the contact list.

### Reproduction steps

Run the sample app on an Android device. Tap on a contact. Hit the delete action on the details screen. Go to your Contact-App on your device and find the contact under "(no name)"  

### Configuration

**Version:** 0.2.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by trinqk** [comment]
@eisdrachl Fixed by PR [#73](https://github.com/fluttercommunity/flutter_contacts/pull/73). Please use the latest version ```contacts_service: ^0.2.4```

**Comment by eisdrachl** [comment]
@trinqk Thank you very much for the fix!
