### ISSUE TITLE
Forces me to migrate flutter app to AndroidX

### ISSUE THREAD

**Issue by ekuprel** [fluttercommunity/flutter_contacts#74]
When using contact service^0.2.4 I ran into a compile errors that lead me to upgrade my flutter app to AndroidX (i.e. https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility)

Is this expected?

**Comment by trinqk** [comment]
Yes, this is expected.

**Comment by lukasgit** [comment]
@ekuprel maybe this link will help https://www.reddit.com/r/FlutterDev/comments/apt4hr/flutter_upgrade_and_android_x_beware_solution/

**Comment by ekuprel** [comment]
Thank you, this link was **very** helpful.
