### ISSUE TITLE
Avatar OK on IOS, not working on Android

### ISSUE THREAD

**Issue by alaindixon** [fluttercommunity/flutter_contacts#77]
Hi All,

When I add a avatar to the contact, it works on IOS but not Android.
Any idea?

Cheers

Alain

**Comment by lukasgit** [comment]
Fixed in PR #82 please update to the latest version 0.2.5

**Comment by budo385** [comment]
I have this issue on 0.2.7
Working on iOS on Android not working.
Does it have to be of  some specific size or what am I doing wrong?
