### ISSUE TITLE
Feature: Get the full image for a contact

### ISSUE THREAD

**Issue by matthewdlloydlp** [fluttercommunity/flutter_contacts#78]
I can get the thumbnail for a contact but it would be nice to have a second call to get the full image for a specific contact so that I can display it larger on a details page.

**Comment by lukasgit** [comment]
@matthewdlloydlp we also welcome the community to participate in adding features

**Comment by lukasgit** [comment]
@matthewdlloydlp added via PR #95 (thank @budo385). Please update to version 0.2.8
