### ISSUE TITLE
Feature request: Notes data field

### ISSUE THREAD

**Issue by megid2** [fluttercommunity/flutter_contacts#80]
First of all, thanks for the plugin! I was wondering about the other contact fields (attributes?), e.g. "notes", that are at least in the Android Contacts API (I have no idea about the iOS contacts API). It would be nice if I could ask the contact service which fields exist, then specify which fields I want. Alternatively, as a simpler solution, could you consider including the notes field?

**Comment by lukasgit** [comment]
Implemented notes field #82

**Comment by megid2** [comment]
Thanks a lot Lukas, and happy easter holidays! (if you have those)
