### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by dboce** [fluttercommunity/flutter_contacts#83]
由于我的xcode版本是最新的Version 10.2.1 (10E1001),使用此插件时总会提示:
The target “contacts_service” contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets.

Use Xcode 10.1 to migrate the code to Swift 4.

我不能回退Xcode版本,但又没有什么好的办法来解决

**Comment by lukasgit** [comment]
Hi @duboce2008 can you please provide the output of your logs? Thanks!

**Comment by dboce** [comment]
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0. This setting can be set in the build settings editor.

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.

**Comment by lukasgit** [comment]
@duboce2008 flutter console output?

**Comment by dboce** [comment]
yes

**Comment by lukasgit** [comment]
> yes

Hi @duboce2008 we need more details. Please use "flutter -v" and post the results. Thanks!

**Comment by lukasgit** [comment]
@duboce2008 please check if issue #85 resolves the problem you're experiencing and let me know the results. Thanks!

**Comment by lukasgit** [comment]
We are not experiencing problems building with Swift, so closing this issue due to no response from @duboce2008.
