### ISSUE TITLE
SWIFT_VERSION not set

### ISSUE THREAD

**Issue by multinethenrik** [fluttercommunity/flutter_contacts#85]
When installing the pods for iOS, the console provides me with following message:

[!] Unable to determine Swift version for the following pods:

- `contacts_service` does not specify a Swift version and none of the targets (`Runner`)
    integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the
    `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

I have tried to set it in the configuration of the pod file, but still the same, so I conclude that there is some kind of tweak I need or a bug in the plugin

**Comment by dars** [comment]
I had the same issue.... Orz

**Comment by remeezp** [comment]
I am having the same issue as well.

**Comment by trinqk** [comment]
This error might occur if you did not include Swift support for iOS code. Please make sure that your app has [Swift support.](https://stackoverflow.com/questions/52244346/how-to-enable-swift-support-for-existing-project-in-flutter)

**Comment by lukasgit** [comment]
@multinethenrik @dars @remeezp 

https://stackoverflow.com/questions/54912188/flutter-plugin-ios-build-fail

Let us know if any of these links have helped so we can close this issue. Thanks!

**Comment by remeezp** [comment]
Hi @lukasgit, I used the link @trinqk posted, but I re-created my project using: 

flutter create <PROJECT_NAME> -i swift -a kotlin

I then copied all my libraries and files back and it worked.

**Comment by dars** [comment]
Hello, @lukasgit I re create my project iOS language to swift
and it's work now 👍 
thank you very much ^^

**Comment by lukasgit** [comment]
@remeezp @dars fantastic! I'll consider this issue resolved.
