### ISSUE TITLE
So, because your_app depends on contacts_service ^0.2.6, version solving failed.

### ISSUE THREAD

**Issue by lambasoft** [fluttercommunity/flutter_contacts#89]
My application depends on contacts_service ^0.2.6, and flutter packages get is failing because contacts_service depends on an older version. The error I'm getting:

```
Because contacts_service >=0.2.1 depends on path_provider ^0.5.0+1 and your_app depends on path_provider ^1.1.0, contacts_service >=0.2.1 is forbidden.
So, because your_app depends on contacts_service ^0.2.6, version solving failed.
```

Can I fix this myself or we need to make contacts_service use the latest version of path_provider through a pull request?

**Comment by lukasgit** [comment]
@lambasoft are you experiencing this issue when using the latest version of contacts_service (0.2.8) ?
