### ISSUE TITLE
Happens as soon as I include the app into my software. No code has been created yet to utilize it.

### ISSUE THREAD

**Issue by pneves001** [fluttercommunity/flutter_contacts#90]
/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.2.6/
    ios/Classes/ContactsServicePlugin.m:2:9: fatal error:
    'contacts_service/contacts_service-Swift.h' file not found
    #import <contacts_service/contacts_service-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the precompiled application for the device.

**Comment by trinqk** [comment]
@pneves001 This error might occur if you did not include Swift support for iOS code. Please make sure that your app has [Swift support.](https://stackoverflow.com/questions/52244346/how-to-enable-swift-support-for-existing-project-in-flutter)

**Comment by lukasgit** [comment]
@pneves001 closing this issue due to no response. Please let us know if trinqk's solution solved the problem. Thanks!
