### ISSUE TITLE
Return birthday field

### ISSUE THREAD

**Issue by Jesse-imuzo** [fluttercommunity/flutter_contacts#92]
Thanks for this plugin, It's great! 

Is there a way to return the birthday field from the phone's contacts?

**Comment by bottee** [comment]
Yes, I would also appreciate the birthday field!

**Comment by lukasgit** [comment]
@Jesse-imuzo @bottee looking into it, thanks!

**Comment by PaddyBadger** [comment]
Thank you @lukasgit, I'd love this too!

**Comment by lukasgit** [comment]
@Jesse-imuzo @bottee @PaddyBadger https://github.com/lukasgit/flutter_contacts/issues/12#issuecomment-526012659

**Comment by lukasgit** [comment]
Please submit issues and PR's to https://github.com/lukasgit/flutter_contacts
