### ISSUE TITLE
Bug: Query return false if have company and firstname setted

### ISSUE THREAD

**Issue by emptyway** [fluttercommunity/flutter_contacts#93]
Platform: Android

I'm trying to find contacts by Company name. works find if the contact only have Company field. but failing if the contact have first name and company fields.  

I believe it's because the query is only by display name. 
https://github.com/fluttercommunity/flutter_contacts/blob/b58b508d08f207dd2065c82ddd61c83d96bc134a/android/src/main/java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java#L167

**Comment by lukasgit** [comment]
@simonlinj are you still experiencing this issue with the latest version 0.2.8 ?
