### ISSUE TITLE
Contact not updating

### ISSUE THREAD

**Issue by nishin-login2** [fluttercommunity/flutter_contacts#97]
I have given both read, write contact permissions in manifest file.
I could fetch contacts and display it in a list. 
But updating a contact is not working.
Below is my code.

```

import 'package:contacts_service/contacts_service.dart';

...


_buildContactList() {
    final contactList = await ContactsService.getContacts().toList();
    return ListView.builder(
        itemCount: contactList.length,
        shrinkWrap: true,
        itemBuilder: (context, index) {
          final Contact item = contactList.elementAt(index);
          return ListTile(
            title: Text(item.displayName),
            onLongPress: () async{
              item.displayName = "Modified ${item.displayName}";
              final result = await ContactsService.updateContact(item);
              print(result); // prints "null"
            },
          );
        });
  }
```

What am I doing wrong?

**Comment by lukasgit** [comment]
@nishin-login2 are you using the latest version?

**Comment by jordy-garcia** [comment]
I have this same issue, when I try to update contact, it erase its phone number and not apply any change

**Comment by lukasgit** [comment]
@nishin-login2 @jordy-garcia please use the latest code from https://github.com/lukasgit/flutter_contacts and let me know if that solves the problem. Thanks!

**Comment by jordy-garcia** [comment]
> @nishin-login2 @jordy-garcia please use the latest code from https://github.com/lukasgit/flutter_contacts and let me know if that solves the problem. Thanks!

Yes It still has the same behaviour, try it in real devices and you'll see. In emulators it works well, but on real devices it erases the phone number

**Comment by YosefAntonius** [comment]
I have seen that the pattern of contacts that cannot be modified have a link to the icloud or to another platform, for this reason it is impossible to modify it .. A contact normally stored in the cell phone if it can be modified. Is there a way to detect if the contact is synchronized or saved normally?

**Comment by lukasgit** [comment]
Please submit issues and PR's to https://github.com/lukasgit/flutter_contacts
