### ISSUE TITLE
Contact custom + operator doesn't copy the displayName

### ISSUE THREAD

**Issue by nashfive** [fluttercommunity/flutter_contacts#98]
Hey there! 
I need to create a copy from an existing Contact so I went this route:
```dart 
Contact newContact = Contact() + contact;
```
But then the original contact's `displayName` is lost. I've noticed that the custom `+` operator doesn't handle the `displayName` property and neither the Contact constructor. 
Is it on purpose? If yes, can you elaborate on why?

My quick workaround:
```dart
Contact copyFrom(Contact contact) => Contact.fromMap(contact.toMap());
```

**Comment by lukasgit** [comment]
@nashfive heads up, I am not the original author of this plugin. This plugin was written early on and has its limitations. The issue you are experiencing might be related to the limitations. We are working on re-writing a new plugin to replace this plugin from the ground up that is clean, secure, flexible, and easy to maintain.

Our resources are limited, but please feel free to contribute to the current plugin with your fixes / improvements. Please see the README for more information on how to contribute. Thanks!
