### ISSUE TITLE
BUILD TARGET flutter_webview_plugin OF PROJECT Pods WITH CONFIGURATION Debug

### ISSUE THREAD

**Issue by jishaofeng89** [fluttercommunity/flutter_contacts#99]
=== #BUILD TARGET flutter_webview_plugin OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:59:
    75: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        _result([FlutterError errorWithCode:[NSString stringWithFormat:@"%d", error.code]
                                                                         ~~   ^~~~~~~~~~
                                                                         %ld  (long)
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:91:
    115: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        NSLog(@"search#searchReGeocode ios端参数: point -> %@, radius -> %f, latLonType -> %d", pointJson, radius, latLonType);
                                                                                           ~~                      ^~~~~~~~~~
                                                                                           %ld                     (long)
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:10:
    81: note: expanded from macro 'NSLog'
    #define NSLog(FORMAT, ...) printf("%s\n", [[NSString stringWithFormat:FORMAT, ##__VA_ARGS__] UTF8String]);
                                                                                    ^~~~~~~~~~~
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:118
    :75: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        _result([FlutterError errorWithCode:[NSString stringWithFormat:@"%d", error.code]
                                                                         ~~   ^~~~~~~~~~
                                                                         %ld  (long)
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:164
    :75: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        _result([FlutterError errorWithCode:[NSString stringWithFormat:@"%d", error.code]
                                                                         ~~   ^~~~~~~~~~
                                                                         %ld  (long)
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:209
    :75: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        _result([FlutterError errorWithCode:[NSString stringWithFormat:@"%d", error.code]
                                                                         ~~   ^~~~~~~~~~
                                                                         %ld  (long)
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:252
    :75: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        _result([FlutterError errorWithCode:[NSString stringWithFormat:@"%d", error.code]
                                                                         ~~   ^~~~~~~~~~
                                                                         %ld  (long)
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:297
    :75: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        _result([FlutterError errorWithCode:[NSString stringWithFormat:@"%d", error.code]
                                                                         ~~   ^~~~~~~~~~
                                                                         %ld  (long)
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:343
    :75: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        _result([FlutterError errorWithCode:[NSString stringWithFormat:@"%d", error.code]
                                                                         ~~   ^~~~~~~~~~
                                                                         %ld  (long)
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:389
    :75: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        _result([FlutterError errorWithCode:[NSString stringWithFormat:@"%d", error.code]
                                                                         ~~   ^~~~~~~~~~
                                                                         %ld  (long)
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:430
    :30: warning: incompatible pointer types assigning to 'NSArray<AMapGeoPolygon *> *' from 'NSArray<NSArray<AMapGeoPoint *> *> *'
    [-Wincompatible-pointer-types]
        routeQuery.avoidpolygons = _routePlanParam.avoidPolygons;
                                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:554
    :11: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
        NSLog([response mj_JSONString]);
              ^~~~~~~~~~~~~~~~~~~~~~~~
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:10:
    71: note: expanded from macro 'NSLog'
    #define NSLog(FORMAT, ...) printf("%s\n", [[NSString stringWithFormat:FORMAT, ##__VA_ARGS__] UTF8String]);
                                                                          ^~~~~~
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:554
    :11: note: treat the string as an argument to avoid this
        NSLog([response mj_JSONString]);
              ^
              @"%@", 
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:10:
    71: note: expanded from macro 'NSLog'
    #define NSLog(FORMAT, ...) printf("%s\n", [[NSString stringWithFormat:FORMAT, ##__VA_ARGS__] UTF8String]);
                                                                          ^
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_base-0.3.5/ios/Classes/search/SearchHandlers.m:560
    :75: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        _result([FlutterError errorWithCode:[NSString stringWithFormat:@"%d", error.code]
                                                                         ~~   ^~~~~~~~~~
                                                                         %ld  (long)
    12 warnings generated.
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/contacts_service-0.2.8/ios/Classes/ContactsServicePlugi
    n.m:4:17: error: definition of 'ContactsServicePlugin' must be imported from module 'contacts_service.ContactsServicePlugin'
    before it is required
    @implementation ContactsServicePlugin
                    ^
    In module 'contacts_service' imported from
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/contacts_service-0.2.8/ios/Classes/ContactsServicePlugi
    n.m:2:
    /Users/administrator/VSCodeProjects/kiss_you_5g/build/ios/Debug-iphonesimulator/contacts_service/contacts_service.framework/Header
    s/ContactsServicePlugin.h:3:12: note: previous definition is here
    @interface ContactsServicePlugin : NSObject<FlutterPlugin>
               ^
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/contacts_service-0.2.8/ios/Classes/ContactsServicePlugi
    n.m:6:4: warning: 'SwiftContactsServicePlugin' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      [SwiftContactsServicePlugin registerWithRegistrar:registrar];
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'contacts_service' imported from
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/contacts_service-0.2.8/ios/Classes/ContactsServicePlugi
    n.m:2:
    /Users/administrator/VSCodeProjects/kiss_you_5g/build/ios/Debug-iphonesimulator/contacts_service/contacts_service.framework/Header
    s/contacts_service-Swift.h:189:12: note: 'SwiftContactsServicePlugin' has been explicitly marked partial here
    @interface SwiftContactsServicePlugin : NSObject <FlutterPlugin>
               ^
    /Users/administrator/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/contacts_service-0.2.8/ios/Classes/ContactsServicePlugi
    n.m:6:4: note: enclose 'SwiftContactsServicePlugin' in an @available check to silence this warning
      [SwiftContactsServicePlugin registerWithRegistrar:registrar];
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning and 1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone XR.

**Comment by lukasgit** [comment]
Hey @jishaofeng89 sorry to hear you're running into trouble. Without seeing your code, it's difficult to debug. Did you follow the example instructions for importing the plugin?

**pubspec.yaml file:**
```
dependencies:  
    contacts_service: ^0.2.8
```

**In your code:**
```
// Import package
import 'package:contacts_service/contacts_service.dart';
```

**Comment by lukasgit** [comment]
Please submit issues and PR's to https://github.com/lukasgit/flutter_contacts
